version: '3.1'
services:
  mariadb:
    image: mariadb:10.7
    container_name: mariadb
    volumes:
    # create persistent docker volume
    - ./data:/var/lib/mysql
    # mount configuration
    - ./config/:/etc/mysql/conf.d
    # network_mode: "host"
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
    # - MYSQL_ROOT_HOST: localhost
      MARIADB_ROOT_HOST: '%'
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: default_db

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u user --password=user
