version: "3.1"
services:
  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=root
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
      - ./redis-dump:/var/lib/redis
    restart: unless-stopped
    # network_mode: host
